main/urls.py
from django.urls import path

from . import views

app_name = 'main'

urlpatterns = [
    path('', views.home, name='home'),
]

story4project/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('story1/', include(('story1.urls', 'story1'), namespace='story1')),
    path('story3/', include(('story3.urls','story3'), namespace='story3')),
    path('story5/', include(('story5.urls','story5'), namespace='story5')),
    path('story6/', include(('story6.urls','story6'), namespace='story6')),
    path('story7/', include(('story7.urls','story7'), namespace='story7')),
    path('story8/', include(('story8.urls','story8'), namespace='story8')),
    path('story9/', include(('story9.urls','story9'), namespace='story9')),
]

story6/urls.py
from django.urls import path

from . import views

app_name = 'story6'

urlpatterns = [
    path('', views.savekegiatan, name='kegiatan'),
    path('<int:id>/', views.peserta, name='peserta'),
    path('<int:id>/savepeserta', views.savepeserta, name='savepeserta')
]

story6/models.py
from django.db import models

class Kegiatan(models.Model):
    nama = models.CharField(max_length=200)

    def __str__(self):
        return self.nama

class Orang(models.Model):
    nama = models.CharField(max_length=200)
    kegiatan = models.ForeignKey(Kegiatan, on_delete=models.CASCADE)

    def __str__(self):
        return self.nama

story6/forms.py
from django import forms
from .models import Kegiatan, Orang

class Input_Kegiatan(forms.ModelForm):
    class Meta:
        model = Kegiatan
        fields = ['nama']

    error_messages = {
        'required' : 'Please Type'
    }
    input_attrs = {
        'type' : 'text',
        'class' : 'form-control'
    }
    nama = forms.CharField(label='', required=True, widget=forms.TextInput(attrs=input_attrs))
class Input_Orang(forms.ModelForm):
    class Meta:
        model = Orang
        fields = ['nama']

    error_messages = {
        'required' : 'Please Type'
    }
    input_attrs = {
        'type' : 'text',
        'class' : 'form-control',
        'placeholder' : 'Nama saya...',
    }
    nama = forms.CharField(label='', required=True, widget=forms.TextInput(attrs=input_attrs))

story6/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
from .forms import Input_Kegiatan, Input_Orang
from .models import Kegiatan, Orang

response = {}


def savekegiatan(request):
    form = Input_Kegiatan(request.POST or None)
    if (form.is_valid and request.method == 'POST'):
        form.save()
    orangs = Orang.objects.all()
    kegiatans = Kegiatan.objects.all()
    response = {'input_kegiatan' : Input_Kegiatan, 'kegiatans':kegiatans, 'orangs':orangs}
    html = 'daftarkegiatan.html'
    return render(request, html, response)
def peserta(request, id):
    kegiatan = Kegiatan.objects.get(id=id)
    response = {'kegiatan' : kegiatan, 'input_orang' : Input_Orang}
    return render(request, "daftarpeserta.html", response)
def savepeserta(request, id):
    form = Input_Orang(request.POST or None)
    if (form.is_valid and request.method == 'POST'):
        kegiatan = Kegiatan.objects.get(id=id)
        Orang.objects.create(nama=request.POST['nama'],kegiatan=kegiatan)
    return HttpResponseRedirect('/story6/')

story6/templates/daftarkegiatan.html
{% extends 'base.html' %}

{% load static %}

{% block meta %}
<title>Daftar Kegiatan Seru</title>
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<link href="https://fonts.googleapis.com/css2?family=Poppins:wght@300;400;500;600;700&display=swap" rel="stylesheet">
<link rel="stylesheet" href="{% static 'css/stylestory3.css' %}">
<style>
    input[type=submit] {
        color: white;
        text-align: center;
        border: none; border-radius: 6px;
    }
    .box {
        width:225px; height:225px;
        background-color: #335b8b;
        display: block;
        border-radius: 25px;
        margin-left: auto; margin-right: auto;
        text-align: center; color:white;
        overflow: auto;
        padding: 5px; line-height: 1.5;
    }
    .row {
        display: flex;
        flex-wrap: wrap;
        width: 80%; margin: auto;
    }
    @media screen and (max-width: 712px) {
        .line {
            margin-left:auto !important;
            margin-right:auto !important;
        }
    }
</style>
{% endblock meta %}

{% block content %}
<div class="container-fluid p-3 my-3 text-white text-md-left text-center">
    <h1 id="greeting">Daftarkan Kegiatan!</h1>
</div>
<div class="container-fluid p-3 text-left text-white" style="background-color: #1d3557;">
    <div style="width: 75%; margin:auto; padding: 50px 0px;">
        <div class="form-group">
            <form action="" method="POST">
                {% csrf_token %}
                Masukkan Kegiatan: {{ input_kegiatan.nama }}<br>
                <input type="submit" value="Submit" style="background-color: #6096ba; padding: 10px 20px;">
            </form>
        </div>
    </div>
</div>
{% if kegiatans %}
<div class="container-fluid p-3 text-md-left text-center" style="background-color: #f2f2f5;">
    <h1 id="daftar" style="color: #1d3557;">Ikuti Kegiatan Seru</h1>
    <hr class="line l" style="width: 50%;">
    <br>
    <div class="container p-3 mt-n5" style="width: 80%; margin: auto;"></div>
        <br>
        <div class="row justify-content-around">
        {% for kegiatan in kegiatans %}
            <div class="col-xs-12 col-sm-6 col-lg-4">
                <div class="box">
                    <br>
                    <p style="line-height: 1.5;"><b><b>{{ kegiatan.nama }}</b></b></p>
                        {% for orang in orangs %}
                        {% if orang.kegiatan.nama == kegiatan.nama %}
                        {{ orang.nama }}<br>
                        {% endif %}
                        {% endfor %}
                    <br>
                    <a href="{% url 'story6:peserta' id=kegiatan.id %}" class="btn btn-primary">Tambah Peserta</a>
                </div>
                <br><br>
            </div>
        {% endfor %}
        </div>
    <br><br>
    </div>
</div>
{% endif %}
{% endblock content %}

story6/templates/daftarpeserta.html
{% extends 'base.html' %}

{% load static %}

{% block meta %}
<title>Daftar Kegiatan Seru</title>
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<link href="https://fonts.googleapis.com/css2?family=Poppins:wght@300;400;500;600;700&display=swap" rel="stylesheet">
<link rel="stylesheet" href="{% static 'css/stylestory3.css' %}">
{% endblock meta %}

{% block content %}
<div class="container-fluid p-3 my-3 text-white text-md-left text-center">
    <h1 id="greeting">Daftar ke {{ kegiatan.nama }}</h1>
</div>
<div class="container-fluid p-3 text-left text-white" style="background-color: #1d3557;">
    <div style="width: 75%; margin:auto; padding: 50px 0px;">
        <div class="form-group">
            <form action="{% url 'story6:savepeserta' id=kegiatan.id %}" method="POST">
                {% csrf_token %}
                Masukkan Nama Anda {{ input_orang.nama }}<br>
                <input type="submit" value="Submit" class="btn btn-primary" style="background-color: #6096ba; padding: 10px 20px;">
            </form>
        </div>
    </div>
</div>
{% endblock content%}