main/urls.py
from django.urls import path

from . import views

app_name = 'main'

urlpatterns = [
    path('', views.home, name='home'),
]

story4project/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('story1/', include(('story1.urls', 'story1'), namespace='story1')),
    path('story3/', include(('story3.urls','story3'), namespace='story3')),
    path('story5/', include(('story5.urls','story5'), namespace='story5')),
    path('story6/', include(('story6.urls','story6'), namespace='story6')),
    path('story7/', include(('story7.urls','story7'), namespace='story7')),
    path('story8/', include(('story8.urls','story8'), namespace='story8')),
    path('story9/', include(('story9.urls','story9'), namespace='story9')),
]

story5/urls.py
from django.urls import path

from . import views

app_name = 'story5'

urlpatterns = [
    path('', views.daftar, name='daftar'),
    path('save', views.save),
    path('read', views.read, name='read'),
    path('detail/<str:id>', views.detail, name='detail'),
    path('delete/<str:id>', views.delete, name='delete')
]

story5/models.py
from django.db import models

class Matkul(models.Model):
    nama = models.CharField(max_length=200)
    dosen = models.CharField(max_length=200)
    sks = models.CharField(max_length=200)
    deskripsi = models.TextField(blank=False, null=False)
    semester = models.CharField(max_length=200)
    kelas = models.CharField(max_length=200, default="")

story5/forms.py
from django import forms
from .models import Matkul

class Input_Form(forms.ModelForm):
    class Meta:
        model = Matkul
        fields = ['nama', 'dosen', 'sks', 'deskripsi', 'semester', 'kelas']

    error_messages = {
        'required' : 'Please Type'
    }
    input_attrs = {
        'type' : 'text',
        'class' : 'form-control'
    }
    nama = forms.CharField(label='', required=True, widget=forms.TextInput(attrs=input_attrs))
    dosen = forms.CharField(label='', required=True, widget=forms.TextInput(attrs=input_attrs))
    sks = forms.CharField(label='', required=True, widget=forms.TextInput(attrs=input_attrs))
    deskripsi = forms.CharField(label='', required=True, widget=forms.Textarea(attrs=input_attrs))
    semester = forms.CharField(label='', required=True, widget=forms.TextInput(attrs=input_attrs))
    kelas = forms.CharField(label='', required=True, widget=forms.TextInput(attrs=input_attrs))

story5/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
from .forms import Input_Form
from .models import Matkul

response = {}

def daftar(request):
    response = {'input_form' : Input_Form}
    return render(request, "daftarmatkul.html",response)
def detail(request, id):
    matkul = Matkul.objects.get(id=id)
    response = {'matkul' : matkul}
    return render(request, "detailmatkul.html", response)
def save(request):
    form = Input_Form(request.POST or None)
    if (form.is_valid and request.method == 'POST'):
        form.save()
        return HttpResponseRedirect('/story5/read')
    else:
        return HttpResponseRedirect('/story5/')
def read(request):
    response = {'input_form' : Input_Form}
    matkuls = Matkul.objects.all()
    response['matkuls'] = matkuls
    html = 'daftarmatkul.html'
    return render(request, html, response)
def delete(request, id):
    matkul = Matkul.objects.get(id=id)
    if request.method == "POST":
        matkul.delete()
        return HttpResponseRedirect('/story5/read')
    response = {'matkul' : matkul}
    return render(request, "detailmatkul.html", response)

story5/templates/daftarmatkul.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
<title>Daftar Matkul Tsanaativa Vinnera</title>
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<link href="https://fonts.googleapis.com/css2?family=Poppins:wght@300;400;500;600;700&display=swap" rel="stylesheet">
<link rel="stylesheet" href="{% static 'css/stylestory3.css' %}">
<style>
    input[type=submit] {
        color: white;
        text-align: center;
        border: none; border-radius: 6px;
    }
    #list {
        width: 75%; margin: auto;
        background-color: #f2f2f5;
        padding: 0px 20px;
    }
    #list th{
        background-color: #456994;
        color: white;
    }
    #list td {
        vertical-align: middle;
    }
    #click {
        text-align: center;
        line-height: 1.5;
    }
    .detail, .detail:hover {
        color: inherit;
    }
    .del {
        text-align: center;
    }
    @media screen and (max-width: 712px) {
        .line {
            margin-left:auto !important;
            margin-right:auto !important;
        }
    }
</style>
{% endblock meta %}

{% block content %}
<div class="container-fluid p-3 my-3 text-white text-md-left text-center">
    <h1 id="greeting">Daftarkan Mata Kuliah!</h1>
</div>
<div class="container-fluid p-3 text-left text-white" style="background-color: #1d3557;">
    <div style="width: 75%; margin:auto; padding: 50px 0px;">
        <div class="form-group">
            <form action="save" method="POST">
                {% csrf_token %}
                Nama Mata Kuliah: {{ input_form.nama }}<br>
                Dosen Pengajar: {{ input_form.dosen }}<br>
                Jumlah SKS: {{ input_form.sks }}<br>
                Deskripsi Mata Kuliah: {{ input_form.deskripsi }}<br>
                Semester Tahun: {{ input_form.semester }}<br>
                Ruang Kelas: {{ input_form.kelas }}<br><br>
                <input type="submit" value="Submit" style="background-color: #6096ba; padding: 10px 20px;">
            </form>
        </div>
    </div>
</div>
{% if matkuls %}
<div class="container-fluid p-3 text-md-left text-center" style="background-color: #f2f2f5;">
    <h1 id="daftar" style="color: #1d3557;">Daftar Mata Kuliah</h1>
    <hr class="line l" style="width: 50%;">
    <p id="click">Klik nama matkul untuk melihat detail matkul.</p>
    <br>
    <table id="list" class="table table-striped table-hover">
        <tr>
        <th>Nama Matkul</th>
        <th></th>
        </tr>
        <tbody>
            {% for matkul in matkuls %}
                <tr>
                    <td><a href="{% url 'story5:detail' id=matkul.id %}" class="detail">{{ matkul.nama }}</a></td>
                    <td class="del">
                        <form action="{% url 'story5:delete' id=matkul.id %}" method="POST">
                            {% csrf_token %}
                            <input type="submit" class="btn btn-danger" name="Hapus" value="Hapus">
                        </form>
                    </td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
    <br><br><br>
</div>
{% endif %}
{% endblock content %}

story5/templates/detailmatkul.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
<title>Daftar Matkul Tsanaativa Vinnera</title>
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<link href="https://fonts.googleapis.com/css2?family=Poppins:wght@300;400;500;600;700&display=swap" rel="stylesheet">
<link rel="stylesheet" href="{% static 'css/stylestory3.css' %}">
<style>
    p {
        line-height: 1.5;
    }
    a {
        color: inherit;
    }
    a.hover {
        color:#6096ba;
    }
</style>
{% endblock meta %}

{% block content %}
<div class="container-fluid p-3 my-3 text-white text-md-left text-center">
    <h1 id="greeting">Detail Mata Kuliah</h1>
</div>

<div class="container-fluid p-3 px-5 text-left text-white" style="background-color: #1d3557;">
    <div class="row mx-md-5 mx-3 px-md-4">
        <div class="col-sm-12 px-md-5"></div>
            <br>
            <p><b><b>Nama Matkul:</b></b><br>{{ matkul.nama }}<br>
            <br><b><b>Dosen Pengajar:</b></b><br>{{ matkul.dosen }}<br>
            <br><b><b>Jumlah SKS:</b></b><br>{{ matkul.sks }}<br>
            <br><b><b>Deskripsi:</b></b><br>{{ matkul.deskripsi }}<br>
            <br><b><b>Semester Tahun:</b></b><br>{{ matkul.semester }}<br>
            <br><b><b>Ruang Kelas:</b></b><br>{{ matkul.kelas }}</p>
            <p></p>
        </div>
    </div>
</div>
<div class="container-fluid px-md-5 pb-2 text-white text-md-right text-center">
    <br>
    <p style="text-decoration: underline;"><a href="{% url 'story5:read' %}">Kembali ke daftar</a><br></p>
</div>
{% endblock content %}