main/urls.py
from django.urls import path

from . import views

app_name = 'main'

urlpatterns = [
    path('', views.home, name='home'),
]

story1/urls.py
from django.urls import path

from . import views

app_name = 'story1'

urlpatterns = [
    path('', views.profile, name='story1'),
]

story3/urls.py
from django.urls import path

from . import views

app_name = 'story3'

urlpatterns = [
    path('aboutme/', views.aboutme, name='aboutme'),
    path('myexperience/', views.myexperience, name='myexperience'),
]

story4project/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('story1/', include(('story1.urls', 'story1'), namespace='story1')),
    path('story3/', include(('story3.urls','story3'), namespace='story3')),
    path('story5/', include(('story5.urls','story5'), namespace='story5')),
    path('story6/', include(('story6.urls','story6'), namespace='story6')),
    path('story7/', include(('story7.urls','story7'), namespace='story7')),
    path('story8/', include(('story8.urls','story8'), namespace='story8')),
    path('story9/', include(('story9.urls','story9'), namespace='story9')),
]

story5/urls.py
from django.urls import path

from . import views

app_name = 'story5'

urlpatterns = [
    path('', views.daftar, name='daftar'),
    path('save', views.save),
    path('read', views.read, name='read'),
    path('detail/<str:id>', views.detail, name='detail'),
    path('delete/<str:id>', views.delete, name='delete')
]

story6/urls.py
from django.urls import path

from . import views

app_name = 'story6'

urlpatterns = [
    path('', views.savekegiatan, name='kegiatan'),
    path('<int:id>/', views.peserta, name='peserta'),
    path('<int:id>/savepeserta', views.savepeserta, name='savepeserta')
]

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <link href='https://fonts.googleapis.com/css?family=Roboto' rel='stylesheet'>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
    {% block meta %}
    {% endblock meta %}
</head>

<body>
  <nav class="navbar navbar-expand-lg navbar-dark sticky-top" style="background-color: #274c78;">
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav">
            <li class="nav-item active">
                <a class="nav-link" href="{% url 'main:home' %}">Home</a>
            </li>
            <li class="nav-item active">
                <a class="nav-link" href="{% url 'story1:story1' %}">Story 1</a>
            </li>
            <li class="nav-item dropdown active">
                <a class="nav-link dropdown-toggle" href="#" id="navDropdownLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Story 3</a>
                <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                    <a class="dropdown-item" href="{% url 'story3:aboutme' %}" style="color: #274c78;">About Me</a>
                    <a class="dropdown-item" href="{% url 'story3:myexperience' %}" style="color: #274c78;">My Experience</a>
                </div>
            </li>
            <li class="nav-item active">
                <a class="nav-link" href="{% url 'story5:daftar' %}">Story 5</a>
            </li>
            <li class="nav-item active">
                <a class="nav-link" href="{% url 'story6:kegiatan' %}">Story 6</a>
            </li>
            <li class="nav-item active">
                <a class="nav-link" href="{% url 'story7:accordion' %}">Story 7</a>
            </li>
            <li class="nav-item active">
                <a class="nav-link" href="{% url 'story8:caribuku' %}">Story 8</a>
            </li>
        </ul>
        <ul class="navbar-nav ml-md-auto d-md-flex">
            {% if user.is_authenticated %}
            <li class="nav-item active">
                <a class="nav-link" href="{% url 'story9:logout' %}">Log Out</a>
            </li>
            {% else %}
            <li class="nav-item active">
                <a class="nav-link" href="{% url 'story9:login' %}">Log In</a>
            </li>
            <li class="nav-item active">
                <a class="nav-link" href="{% url 'story9:register' %}">Sign Up</a>
            </li>
            {% endif %}
        </ul>
    </div>
  </nav>
{% block content %}
{% endblock content %}
</body>
</html>