main/urls.py
from django.urls import path

from . import views

app_name = 'main'

urlpatterns = [
    path('', views.home, name='home'),
]

story4project/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('story1/', include(('story1.urls', 'story1'), namespace='story1')),
    path('story3/', include(('story3.urls','story3'), namespace='story3')),
    path('story5/', include(('story5.urls','story5'), namespace='story5')),
    path('story6/', include(('story6.urls','story6'), namespace='story6')),
    path('story7/', include(('story7.urls','story7'), namespace='story7')),
    path('story8/', include(('story8.urls','story8'), namespace='story8')),
    path('story9/', include(('story9.urls','story9'), namespace='story9')),
]

story9/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views

from . import views
from .forms import LoginForm

app_name = 'story9'

urlpatterns = [
    path('register/', views.register, name='register'),
    path('login/', auth_views.LoginView.as_view(template_name='login.html', form_class=LoginForm), name='login'),
    path('', views.welcome, name='welcome'),
    path('logout/', auth_views.LogoutView.as_view(template_name='logout.html'), name='logout'),
]

story9/models.py
from django.db import models

# Create your models here.

story9/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm

class RegisterForm(UserCreationForm):
    username = forms.CharField(label="Username", widget=forms.TextInput(attrs={'class': 'form-control'}), help_text='Wajib diisi. Maksimal 150 karakter. Hanya dapat memuat huruf, angka dan @/./+/-/_.')
    password1 = forms.CharField(label = "Password", widget=forms.PasswordInput(attrs={'class': 'form-control'}), help_text="Harus terdiri dari minimal 8 karakter, dilarang hanya berisi angka.")
    password2 = forms.CharField(label= "Konfirmasi Password", widget=forms.PasswordInput(attrs={'class': 'form-control'}), help_text='Masukkan password pada kolom sebelumnya untuk verifikasi.')

    class Meta(UserCreationForm.Meta):
        model = User
        fields = ['username', 'password1', 'password2']
        labels = {
            'username':'Username',
            'password1' : 'Password',
            'password2' : 'Password Confirmation',
        }

class LoginForm(AuthenticationForm):
    username = forms.CharField(label="Username", widget=forms.TextInput(attrs={'class': 'form-control'}))
    password = forms.CharField(label="Password", widget=forms.PasswordInput(attrs={'class': 'form-control'}))

    def setUp(self):
        User.objects.create_user('username', password='password')

story9/views.py
from django.shortcuts import render, redirect
from .forms import RegisterForm
from django.contrib import messages

def register(request):
    if request.method == 'POST':
        form = RegisterForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            messages.success(request, f'Akun {username} berhasil dibuat!')
            return redirect('story9:login')
        else:
            messages.error(request, f'Akun gagal dibuat, ulangi kembali')
    else:
        form = RegisterForm()
    return render (request, 'register.html', {'form' : form})

def welcome(request):
    return render(request, 'welcome.html')

story9/templates/login.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
<title>Log In</title>
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<link href="https://fonts.googleapis.com/css2?family=Poppins:wght@300;400;500;600;700&display=swap" rel="stylesheet">
<link rel="stylesheet" href="{% static 'css/stylestory3.css' %}">
<link rel="stylesheet" href="{% static 'stylestory9.css' %}">
{% endblock meta %}

{% block content %}
<div class="content">
<div class="register-box text-white">
        <form method="POST">
            {% csrf_token %}
            <fieldset class="form-group">
                <h1>Log In</h1>
                <hr class="lineBlue">
                <div class="success">
                    {% if messages %}
                    {% for message in messages %}
                        <small>{{ message }}</small><br>
                    {% endfor %}
                    {% endif %}
                </div>
                {% for field in form %}
                {{ field.label }}:<br>
                {{ field }}<br>
                {% endfor %}
            </fieldset>
            <br>
            <div class="form-group">
                <button class="btn btn-primary" type="submit">Login</button>
            </div>
        </form>
        <div>
            <small class="text-muted">
                Belum punya akun? <a href="{% url 'story9:register' %}">Sign Up</a>
            </small>
        </div>
    </div>
</div>
{% endblock content %}

story9/templates/logout.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
<title>Log Out</title>
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<link href="https://fonts.googleapis.com/css2?family=Poppins:wght@300;400;500;600;700&display=swap" rel="stylesheet">
<link rel="stylesheet" href="{% static 'css/stylestory3.css' %}">
<link rel="stylesheet" href="{% static 'stylestory9.css' %}">
{% endblock meta %}

{% block content %}
<div class="content">
<div class="register-box text-white">
    <h1>Anda berhasil logout.</h1>
    <hr class="lineBlue" style="margin-bottom: 20px;">
    <div style="text-align: center;">
        <small class="text-muted">
            <a href="{% url 'story9:login' %}">Login kembali</a>
        </small>
    </div>
</div>
</div>
{% endblock content %}

story9/templates/register.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
<title>Sign Up</title>
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<link href="https://fonts.googleapis.com/css2?family=Poppins:wght@300;400;500;600;700&display=swap" rel="stylesheet">
<link rel="stylesheet" href="{% static 'css/stylestory3.css' %}">
<link rel="stylesheet" href="{% static 'stylestory9.css' %}">
{% endblock meta %}

{% block content %}
<div class="content">
<div class="register-box text-white">
    <form method="POST">
        {% csrf_token %}
        <fieldset class="form-group">
            <h1>Buat Akun Baru</h1>
            <hr class="lineBlue">
            <div class="error">
                {% if messages %}
                {% for message in messages %}
                    <small>{{ message }}</small><br>
                {% endfor %}
                {% endif %}
            </div>
            {% for field in form %}
            {{ field.label }}:<br>
            {{ field }}
            <small>{{ field.help_text }}</small><br><br>
            {% endfor %}
        </fieldset>
        <div class="form-group">
            <button class="btn btn-primary" type="submit">Sign Up</button>
        </div>
    </form>
    <div>
        <small class="text-muted">
            Sudah punya akun? <a href="{% url 'story9:login' %}">Log In</a>
        </small>
    </div>
</div>
</div>
{% endblock content %}

story9/templates/welcome.html
{% extends 'base.html' %}

{% load static %}

{% block meta %}
<title>Selamat Datang di Story PPW Vivin</title>
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<link href="https://fonts.googleapis.com/css2?family=Poppins:wght@300;400;500;600;700&display=swap" rel="stylesheet">
<link rel="stylesheet" href="{% static 'css/stylestory3.css' %}">
<link rel="stylesheet" href="{% static 'stylestory9.css' %}">
{% endblock meta %}

{% block content %}
<div class="content">
    <div class="register-box text-white">
        {% if user.is_authenticated %}
        <h1>Selamat datang, {{ user.username }}.</h1>
        <hr class="lineBlue" style="margin-bottom: 20px;">
        <div style="text-align: center;">
            <small class="text-muted">
                <a href="{% url 'main:home' %}">Kembali ke home</a>
            </small>
        </div>
        {% else %}
        <h1>Anda harus login terlebih dahulu.</h1>
        <hr class="lineBlue" style="margin-bottom: 20px;">
        <div style="text-align: center;">
            <small class="text-muted">
                <a href="{% url 'story9:login' %}">Login</a> atau <a href="{% url 'story9:register' %}">buat akun baru</a>
            </small>
        </div>
        {% endif %}
    </div>
</div>

{% endblock content %}